import type { TemplateTableColumn } from './types'

export const TEMPLATE_TREE_PROPS = {
  children: 'children',
  label: 'name',
  isLeaf: 'leaf'
} as const

export const TEMPLATE_FILE_TABLE_COLUMNS: TemplateTableColumn[] = [
  { type: 'checkbox', width: 80 },
  { width: 120, field: 'id', title: 'ID' },
  { width: 200, field: 'pppName', title: '一级项目类别名称' },
  { width: 200, field: 'ppName', title: '二级项目类别名称' },
  { width: 200, field: 'pname', title: '三级项目类别名称' },
  { width: 200, field: 'name', title: '四级项目类别名称' },
  { width: 180, field: 'code', title: '项目类别编码' },
  { width: 120, field: 'hiberarchy', title: '层级' },
  { width: 200, field: 'yjfl', title: '一级分类' },
  { width: 200, field: 'ejfl', title: '二级分类' },
  { width: 200, field: 'sjfl', title: '三级分类' },
  { width: 200, field: 'dyxzCode', title: '单元性质' },
  { width: 120, field: 'ysbzCodeName', title: '预算编制方式' },
  { width: 120, field: 'ysspgn', title: '预算审批功能' },
  { width: 120, field: 'byskz', title: '包预算控制' },
  { width: 120, field: 'hasprovince', title: '预算编制审批' },
  { width: 120, field: 'sxyskz', title: '事项预算控制' },
  { width: 120, field: 'sflr', title: '是否录入' },
  { width: 120, field: 'xmbtolerance', title: '项目包容差(%)' },
  { width: 120, field: 'sfyxjdys', title: '是否允许机动预算' },
  { width: 120, field: 'sfglzc', title: '是否关联资产' },
  { width: 120, field: 'sfxyxqsh', title: '是否需要需求审核' },
  { width: 120, field: 'sfxylhhs', title: '是否需要联合会审' },
  { width: 120, field: 'sfywdj', title: '是否业务冻结' },
  { width: 120, field: 'zcsjfl', title: '资产三级分类' },
  { width: 120, field: 'expenseCategory', title: '费用类别' },
  { width: 120, field: 'cblb', title: '成本类别' },
  { width: 120, field: 'ysly', title: '预算来源' },
  { width: 120, field: 'jhlx', title: '计划类型' },
  { width: 120, field: 'yssfkz', title: '预算释放控制' },
  { width: 120, field: 'mbzkkz', title: '目标总控值控制(普通包)' },
  { width: 120, field: 'mbztolerance', title: '目标值容差' },
  { width: 360, field: 'cbjdlc', title: '储备阶段流程' },
  { width: 120, field: 'sfjyzdtx', title: '是否校验事项必填' },
  { width: 120, field: 'sfgmblr', title: '是否允许规模包录入' },
  { width: 120, field: 'sfxmlr', title: '是否需求录入' },
  { width: 120, field: 'gbdksfywdj', title: '关闭打开是否业务冻结' },
  { width: 180, field: 'qgcCode', title: '过程名称' },
  { width: 120, field: 'provincialManagementOffice', title: '省管处室' },
  { width: 120, field: 'processingMode', title: '处理模式' },
  { width: 120, field: 'tabType', title: '页签类型' },
  { width: 220, field: 'zdtx', title: '重点投向' },
  { width: 120, field: 'xtly', title: '系统来源' },
  { width: 120, field: 'isZgs', title: '是否子公司' },
  { width: 120, field: 'isSgs', title: '是否省公司' },
  { width: 120, field: 'zjsx', title: '资金属性' },
  { width: 120, field: 'mbzGkjb', title: '目标值管控级别' },
  { width: 130, field: 'mbzZkjd', title: '是否目标值总控节点' },
  { width: 130, field: 'mbzYzx', title: '是否目标值一致性' },
  { width: 180, field: 'cnx', title: '承诺项编码' },
  { width: 300, field: 'cnxName', title: '承诺项名称' },
  { width: 120, field: 'isGjPspfwj', title: '是否需要挂接评审及批复文件' },
  { width: 120, field: 'isBkk', title: '不可控标识' },
  { width: 120, field: 'status', title: '状态' },
  { width: 120, field: 'stoptime', title: '停用时间' }
]
