interface EditParams {
  byskz: string
  zdtxName: string
  cbjdlc: string
  cblb: string
  dyxzCode: string
  ejfl: string
  expenseCategory: string
  gbdksfywdj: string
  hasprovince: string
  jhlx: string
  mbzkkz: string
  mbztolerance: string
  processingMode: string
  provincialManagementOffice: string
  qgcCode: string
  sfglzc: string
  sfgmblr: string
  sfjyzdtx: string
  sflr: string
  sfxmlr: string
  sfxylhhs: string
  sfxyxqsh: string
  sfywdj: string
  sfyxjdys: string
  sjfl: string
  sxyskz: string
  tabType: string
  xmbtolerance: string
  yjfl: string
  ysbzCode: string
  ysly: string
  yssfkz: string
  ysspgn: string
  zcsjfl: string
  xtly: string
  tghsJe: string
  tghsRjh: string
  zyxtyys: string
  csbl: string
  ysbgSfkyxgztz: string
  xqlrEdit: string
  [key: string]: any
}
