export interface RowVO {
  xmid: string
  xmmc: string
  xmbm: string
  gwxmbm: string
  xmbmc: string
  circulStatus: string
  circulStatusName: string
  auditStatus: string
  gbdksfywdj: string
  amount: string
  yqljtzjh: string
  yqljcwzc: string
  xmljwcl: string
  dnys: string
  dntzjh: string
  dncwzc: string
  dnxmcn: string
  ljxmcn: string
  ndyswcl: string
  zjgcye: string
  zjgckpye: string
  ljzzje: string
  ljcn: string
  cnx1: string
  proType: string
  proTypeId: string
  yjfl: string
  yjflName: string
  ejfl: string
  ejflName: string
  sjfl: string
  sjflName: string
  xmxz: string
  xmxzName: string
  yjdw: string
  yjdwName: string
  ejdw: string
  ejdwName: string
  gkbm: string
  gkbmName: string
  dydj: string
  nd: string
  ispackname: string
  publisetime: string
  jyys: string
  kgsj: string
  yjwcsj: string
  jzyy: string
  erpgbdkfhxx: string
  erpgbdkzt: string
  erpgbdkztName: string
  jhxttsfhxx: string
  jhxttszt: string
  jhxttsztName: string
  xmgbdkzt: string
  xmgbdkztName: string
  yssffhxx: string
  yssfzt: string
  yssfztName: string
  zbcbFlag: string
  ctbm: string
}

export interface SearchForm {
  xmmc: string
  xmbm: string
  gwxmbm: string
  xmbmc: string
  dwlable: string[]
  dwtreedata: string[]
  ndyswcl_start_qj: string
  ndyswcl_start_num: string
  ndyswcl_end_qj: string
  ndyswcl_end_num: string
  xmljwcl_start_qj: string
  xmljwcl_start_num: string
  xmljwcl_end_qj: string
  xmljwcl_end_num: string
  ysqj_start: string
  circul_status: string
  ysqj_end: string
  nd: string
  yd_start: string
  yd_end: string
  yjdw: string
  ejdw: string
  yjfl: string
  ejfl: string
  sjfl: string
  xmxz: string
  xmlx_id: string
  yssfzt: string
  publisetime_start: string
  publisetime_end: string
  gbdk_status: string
  xmlx_id_arr: string[]
  xmxz_arr: string[]
  ispack: string
}
